spring.config.import=classpath:framework-default.properties,classpath:security-default.properties,classpath:utility-default.properties
spring.application.name=blog-backend
server.port=8082
# \u914D\u7F6E\u6587\u4EF6\u5206\u73AF\u5883
spring.profiles.active=@profileActive@